### ISSUE TITLE
Docker java container runtime exception

### ISSUE THREAD

**Issue by acidghost** [sbilinski/scalatra-mongodb-seed#2]
I'm getting a RuntimeException when running `sbt docker`:
`Error: image dockerfile/java:latest not found`

Maybe the docker image name has changed or updated his repo? I'm totally new to docker..

**Comment by acidghost** [comment]
I made a pull request with updated build.sbt and some comment to make it work.

Also having mongodb in a separate container can improve the microservices architecture! :smile:

**Comment by sjednac** [comment]
Solved by #3
